# Write your MySQL query statement below
SELECT EMPLOYEE_ID, DEPARTMENT_ID FROM (SELECT EMPLOYEE_ID,DEPARTMENT_ID,COUNT(EMPLOYEE_ID) AS CNT FROM EMPLOYEE  GROUP BY EMPLOYEE_ID) T1 WHERE CNT=1
UNION
SELECT EMPLOYEE_ID,DEPARTMENT_ID FROM EMPLOYEE WHERE PRIMARY_FLAG='Y'